//
//  SentencePieceTokenizerTests.swift
//  mimika-ai-voice-studioTests
//
//  Validates that Swift's Viterbi-based SentencePiece BPE encoder produces byte-identical token IDs to the canonical `sentencepiece` library across a representative English corpus.
//
//  The fixtures file (`Fixtures/tokenizer_parity.json`) is generated by `scripts/generate_tokenizer_parity_fixtures.py` using the same `tokenizer.model` the app ships. Re-run that script whenever the corpus or the tokenizer model changes.
//
//  A regression here means the model is being fed different tokens than it was trained on, which produces audible mispronunciations (the original "friends → frainds" bug class).
//
//  XCTest, not Swift Testing — project convention (CLAUDE.md).
//

import Foundation
import XCTest

@testable import mimika_ai_voice_studio

// MARK: - SentencePieceTokenizer parity

final class SentencePieceTokenizerTests: XCTestCase {

    private struct Fixture: Decodable {
        let text: String
        let expectedIds: [Int32]

        enum CodingKeys: String, CodingKey {
            case text
            case expectedIds = "expected_ids"
        }
    }

    private static let fixtures: [Fixture] = {
        // This test target doesn't ship resources as an SPM module bundle. Load the fixtures file directly from the source-relative path resolved at compile time via #filePath.
        let path = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/tokenizer_parity.json")
        guard let data = try? Data(contentsOf: path),
              let fixtures = try? JSONDecoder().decode([Fixture].self, from: data) else {
            return []
        }
        return fixtures
    }()

    func test_fixtureFileLoadsWithNonZeroCount() {
        XCTAssertFalse(Self.fixtures.isEmpty, "tokenizer_parity.json missing or unreadable")
    }

    func test_allFixturesMatchCanonicalSentencePiece() throws {
        let tok = try SentencePieceTokenizer()

        // Pad to something larger than the longest fixture so we don't hit the overflow guard.
        let paddedLength = 256

        var failures: [(text: String, expected: [Int32], actual: [Int32])] = []
        for fixture in Self.fixtures {
            let (padded, length) = try tok.encode(fixture.text, paddedLength: paddedLength)
            let actual = Array(padded.prefix(length))
            if actual != fixture.expectedIds {
                failures.append((fixture.text, fixture.expectedIds, actual))
            }
        }

        if !failures.isEmpty {
            for f in failures {
                print("PARITY FAIL")
                print("  text:     \(f.text.debugDescription)")
                print("  expected: \(f.expected)")
                print("  actual:   \(f.actual)")
            }
        }
        XCTAssertTrue(
            failures.isEmpty,
            "\(failures.count) of \(Self.fixtures.count) fixtures differ from canonical SentencePiece"
        )
    }

    // MARK: - Targeted regressions
    // Direct assertions for the specific words that motivated the rewrite. These guard against regressing to greedy longest-match (which produced wrong segmentations even though some fixtures might still pass).

    func test_friendsEncodesToCanonicalIDs() throws {
        try assertEncoding(of: "friends", equals: [260, 636, 261])
    }

    func test_perfectLowercaseEncodesToCanonicalIDs() throws {
        try assertEncoding(of: "perfect", equals: [324, 1318])
    }

    func test_perfectCapitalizedEncodesToCanonicalIDs() throws {
        try assertEncoding(of: "Perfect", equals: [497, 1318])
    }

    /// Encodes one word and compares against the canonical id sequence.
    private func assertEncoding(
        of word: String,
        equals expected: [Int32],
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let tok = try SentencePieceTokenizer()
        let (padded, length) = try tok.encode(word, paddedLength: 16)
        let actual = Array(padded.prefix(length))
        XCTAssertEqual(actual, expected, "got \(actual)", file: file, line: line)
    }
}
